server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.36.150
    port: 5672
    username: shindou
    password: shindou
    virtualHost: "/"
