server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.36.150
    port: 5672
    username: shindou
    password: shindou
    virtualHost: "/"
  freemarker:
    cache: false   #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0

eureka:
  client:
    register-with-eureka: true  #注册服务，是否将自己注册到eureka服务中
    fetch-registry: true        #服务发现，是否从eureka中获取注册信息
    service-url:       #eureka客户端与eureka服务端的交互地址，高可用状态配置对方地址，单机状态配置自己的
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true    #将自己的IP地址注册到eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}  #指定实例id
