server:
  port: ${PORT:50101}

spring:
  application:
    name: xc-govern-center

eureka:
  client:
    register-with-eureka: true  #注册服务，是否将自己注册到eureka服务中
    fetch-registry: true        #服务发现，是否从eureka中获取注册信息
    service-url:       #eureka客户端与eureka服务端的交互地址，高可用状态配置对方地址，单机状态配置自己的
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}

  server:
    enable-self-preservation: false   #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000    #注册服务表清理间隔

  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}