server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.41.150
    port: 5672
    username: shindou
    password: shindou
    virtualHost: "/"
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1  #routingkey为门户站点ID