server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.36.150
    port: 5672
    username: guest
    password: guest
    virtualHost: "/"
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingkey: 5c9a4217ab2bdc33a4e5eb41  #routingkey为门户站点ID